### ISSUE TITLE
Having an issue with running inference.

### ISSUE THREAD

**Issue by thtranos** [lchdl/annotation_free_wmh_seg#2] opened 2024-01-23 12:01 UTC
I would really appreciate if you could help me find the problem that causes this error.

I will input only the last few lines of the error that have meaning, my prompt was:

`DeepWMH_predict -i example_flair.nii -n 0 -m models -o output`

Error:

```
using model stored in  /Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['0']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
selected cases to predict: ['0']
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, ['all']
set max_num_epochs=300
set num_batches_per_epoch=250
no validation set? False
using the following model files:  ['/Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1/all/model_best.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/Users/theodoretranos/anaconda3/envs/brain/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict_simple.py", line 214, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 412, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 211, in predict_cases
    for preprocessed in preprocessing:
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 112, in preprocess_multithreaded
    pr.start()
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/theodoretranos/anaconda3/envs/brain/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x14f590430>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed

>>> ** Unexpected return value "1" from command:

>>> nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 

>>> ** Process will exit now.

Error occurred (code 1) when executing command:
"nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 "
```

Theodore Tranos

**Comment by lchdl** [comment] 2024-01-23 12:12
Hi thtranos, I am now fixing the problem you just met.
Could you please provide the following information so that I can reproduce the error? 
* detailed information about the operating system you are using (such as Ubuntu version, etc.).
* your Python version
* run "pip list" to list all your 3rd-party package versions

Also, from the error message you just provided, I am assuming that the bug is from Python's **pickle**, since different Python version have different storage format for pickle (*.pkl) file. The model was trained using Python 3.7.1, so maybe your python version is not compatible with this.

**Comment by lchdl** [comment] 2024-01-23 12:19
Hi thtranos @thtranos , try running inference using **Python 3.7** and see if that helps.

**Comment by thtranos** [comment] 2024-01-23 18:35
Ok, ill provide all the information that I can.
I'm using Anaconda,

VENV with Python 3.10.13 (since 3.11 seems to have some problems with those dependencies but i guess there is still something wrong going on)

My OS is MAC Apple M2 Sonoma 14.3

i'm passing the integrity script just fine without errors.

(Also, I should mention that i'm not entirely sure if I provide the input prompt right. the input is FLAIR .ni photos right?, also the case is just a label for the images !?)

Here's is the pip list:

Package            Version      Editable project location
------------------ ------------ ----------------------------------------------------------------
batchgenerators    0.25
certifi            2023.11.17
charset-normalizer 3.3.2
contourpy          1.2.0
cssselect2         0.7.0
cycler             0.12.1
deepwmh            1.0.0        /Users/theodoretranos/Desktop/DeepWMH
dicom2nifti        2.4.10
et-xmlfile         1.1.0
filelock           3.13.1
fonttools          4.47.2
fsspec             2023.12.2
future             0.18.3
idna               3.6
imageio            2.13.2
Jinja2             3.1.3
joblib             1.3.2
kiwisolver         1.4.5
lazy_loader        0.3
linecache2         1.0.0
lxml               5.1.0
MarkupSafe         2.1.4
matplotlib         3.8.2
MedPy              0.4.0
mpmath             1.3.0
networkx           3.2.1
nibabel            3.2.1
nnunet             1.6.6        /Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop
numpy              1.22.4
openpyxl           3.0.9
packaging          23.2
pandas             2.2.0
patsy              0.5.6
pillow             10.2.0
pip                23.3.1
psutil             5.9.8
pydicom            2.4.4
pyparsing          3.1.1
python-dateutil    2.8.2
python-gdcm        3.0.23
pytz               2023.3.post1
PyWavelets         1.5.0
reportlab          3.6.9
requests           2.31.0
scikit-image       0.19.3
scikit-learn       1.4.0
scipy              1.7.3
setuptools         68.2.2
SimpleITK          2.3.1
six                1.16.0
statsmodels        0.13.2
svglib             1.2.1
sympy              1.12
threadpoolctl      3.2.0
tifffile           2023.12.9
tinycss2           1.2.1
torch              2.1.2
traceback2         1.4.0
typing_extensions  4.9.0
tzdata             2023.4
unittest2          1.1.0
urllib3            2.1.0
webencodings       0.5.1
wheel              0.41.2
XlsxWriter         1.4.3

As I said to the previous issue, thanks for replying ultra fast, really appreciate your diligence.
I find your work wonderful.

Theodore Tranos.

**Comment by lchdl** [comment] 2024-01-23 19:41
Hi thtranos, from what I see in your latest post, I am afraid there are several things that are not right from my own perspective. 
* I have not tested DeepWMH on a MAC; the entire toolkit has only been fully tested on **Ubuntu systems** running on **Intel CPUs**.
* The segmentation performance of DeepWMH was only validated using NVIDIA GPUs. There might be some potential issues if you run DeepWMH on Apple hardware. 
* Did you install DeepWMH in a **completely clean** virtual environment? 
* DeepWMH has not been fully tested in **Python 3.10** (or, more precisely, the entire toolkit was only tested using Python 3.7 when it was released).
* You have installed PyTorch 2.x, but DeepWMH was tested using **PyTorch 1.x**.

**NOTE**: The problem you encountered was not caused by DeepWMH itself, but rather from **nnU-Net**, which DeepWMH depends on. That's why you passed the integrity check but failed the network inference. So my suggestion is that you might need to do the following steps:
* Run DeepWMH on a machine with **Intel/AMD CPUs** (though MAC might also work; I'm not certain if DeepWMH runs on MAC, but if so, cheers!)
* Create a whole **new** virtual environment from scratch using anaconda with **Python 3.7** and **torch 1.x** (e.g: torch 1.13) . Then in that enviroment, install DeepWMH by following the steps in README.md.

Here are the details of my environment when developing DeepWMH:
* Ubuntu 16.04 LTS
* Python 3.7.1
* torch 1.13.1 with CUDA GPU support
* RTX 2080Ti
* Intel Xeon CPU E5-2680 v4, x86_64 arch

Finally, regarding your last question, you only need to provide the T2FLAIR image(s) along with their respective subject name(s). Labels are not required as the entire pipeline operates without annotations (unsupervised). For instance, if you have a T2FLAIR scan located at '**/a/b/c/brain.nii.gz**' belonging to an individual named '**Bob**', you should use the following command:

> DeepWMH_predict -i **/a/b/c/brain.nii.gz** -n **Bob** -m <model_install_dir> -o <output_folder> -g <gpu_id>

As most MR images are stored in the gzipped NIFTI format, it is expected that all filenames will end with '*.nii.gz'.

Looking forward to your reply.

**Comment by lchdl** [comment] 2024-01-23 20:04
Hi thtranos @thtranos, I have made a fix to the repo https://github.com/lchdl/nnUNet_for_DeepWMH, please **git pull** the latest version of **nnUNet_for_DeepWMH** to see if that fixes the problem. I have replaced the softmax_helper lambda to regular function definition https://github.com/lchdl/nnUNet_for_DeepWMH/commit/3741df14e955f06e82f3f40772ae543b2a26e843.

**Comment by thtranos** [comment] 2024-01-23 20:36
I did all things mentioned, 

made a clean anaconda with python3.8.18 (it was the oldest I could use right now, I dont think that python is the problem tho)

The previous times that i got it run to preprocessing it took 10 mins. Now it showed up instantly, I don't know if this indicates something.

It's probably a fault of my end, I'm new on the field of the medical data, I don't really understand the .nii formats to be fair, for example I may put wrong data in the input (you mentioned .nii.gz while I input .gz)

**my pip list now looks like this,**

Package             Version      Editable project location
------------------- ------------ ----------------------------------------------------------------
batchgenerators     0.25
certifi             2023.11.17
charset-normalizer  3.3.2
contourpy           1.1.1
cssselect2          0.7.0
cycler              0.12.1
deepwmh             1.0.0        /Users/theodoretranos/Desktop/DeepWMH
dicom2nifti         2.4.10
et-xmlfile          1.1.0
fonttools           4.47.2
future              0.18.3
idna                3.6
imageio             2.13.2
importlib-resources 6.1.1
joblib              1.3.2
kiwisolver          1.4.5
lazy_loader         0.3
linecache2          1.0.0
lxml                5.1.0
matplotlib          3.7.4
MedPy               0.4.0
networkx            3.1
nibabel             3.2.1
nnunet              1.6.6        /Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop
numpy               1.22.4
openpyxl            3.0.9
packaging           23.2
pandas              2.0.3
patsy               0.5.6
pillow              10.2.0
pip                 23.3.1
psutil              5.9.8
pydicom             2.4.4
pyparsing           3.1.1
python-dateutil     2.8.2
python-gdcm         3.0.23
pytz                2023.3.post1
PyWavelets          1.4.1
reportlab           3.6.9
requests            2.31.0
scikit-image        0.19.3
scikit-learn        1.3.2
scipy               1.7.3
setuptools          68.2.2
SimpleITK           2.3.1
six                 1.16.0
statsmodels         0.13.2
svglib              1.2.1
threadpoolctl       3.2.0
tifffile            2023.7.10
tinycss2            1.2.1
torch               1.13.1
traceback2          1.4.0
typing_extensions   4.9.0
tzdata              2023.4
unittest2           1.1.0
urllib3             2.1.0
webencodings        0.5.1
wheel               0.41.2
XlsxWriter          1.4.3
zipp                3.17.0

**Error:**

```
preprocessing : |==================| 100% << 1s|0s                             
nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 

Customized nnU-Net. The following changes were made:
==============
== TRAINING ==
==============
* disabled data unpacking to speed up training (reduced IO).
* changed default training epochs from 1000 to 300.
* changed 'pin_memory' to 'False'.
* when fold='all', 20% of the training samples will be randomly selected and used in validation.
* 'nnUNetTrainerV2' now support manually setting the number of training epochs and batches (use '-b' and '-e').
* add '--noval' to tell the program not use validation set during training.
* use '--custom_val_cases XXX YYY ...' and set fold to 'all' to manually assign validation set cases.
* use '--save_every_epoch' to save models from all epochs.
* add '--softmax' to save softmax values of validation set samples.
===============
== INFERENCE ==
===============
* add '--selected_cases XXX YYY ...' when inference will only predict the selected test subjects (XXX YYY ...) .
* add '--softmax' to save softmax values of test set samples.
============
== OTHERS ==
============
* removed unused codes.
* minor bug fixes...

using model stored in  /Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['0']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
selected cases to predict: ['0']
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, ['all']
set max_num_epochs=300
set num_batches_per_epoch=250
no validation set? False
using the following model files:  ['/Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1/all/model_best.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/Users/theodoretranos/anaconda3/envs/brain2/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict_simple.py", line 214, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 412, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 211, in predict_cases
    for preprocessed in preprocessing:
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 112, in preprocess_multithreaded
    pr.start()
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'nnUNetTrainerV2.initialize_network.<locals>.<lambda>'

>>> ** Unexpected return value "1" from command:

>>> nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 

>>> ** Process will exit now.

Error occurred (code 1) when executing command:
"nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 "
```

**Comment by lchdl** [comment] 2024-01-23 20:40
> Hi thtranos @thtranos, I have made a fix to the repo https://github.com/lchdl/nnUNet_for_DeepWMH, please **git pull** the latest version of **nnUNet_for_DeepWMH** to see if that fixes the problem. I have replaced the softmax_helper lambda to regular function definition [lchdl/nnUNet_for_DeepWMH@3741df1](https://github.com/lchdl/nnUNet_for_DeepWMH/commit/3741df14e955f06e82f3f40772ae543b2a26e843).

@thtranos try this, just re-download **nnUNet_for_DeepWMH**, unzip and overwrite the old code. Then run inference again to see what happens.

**Comment by lchdl** [comment] 2024-01-23 20:57
@thtranos, download **nnUNet_for_DeepWMH** from here https://github.com/lchdl/nnUNet_for_DeepWMH/tree/lchdl-patch-1, unzip and overwrite to the original location. I made a quick fix and you can test if it can work.

**Comment by thtranos** [comment] 2024-01-24 08:57
@lchdl

Greetings Ichdl!

Regarding:

> @thtranos, download **nnUNet_for_DeepWMH** from here https://github.com/lchdl/nnUNet_for_DeepWMH/tree/lchdl-patch-1, unzip and overwrite to the original location. I made a quick fix and you can test if it can work.

I copied the contents and pasted them to nnUNet_for_DeepWMH-develop folder (overwrite), i still get a this similar error:

preprocessing : |==================| 100% << 1s|0s                             
nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 

Customized nnU-Net. The following changes were made:
==============
== TRAINING ==
==============
* disabled data unpacking to speed up training (reduced IO).
* changed default training epochs from 1000 to 300.
* changed 'pin_memory' to 'False'.
* when fold='all', 20% of the training samples will be randomly selected and used in validation.
* 'nnUNetTrainerV2' now support manually setting the number of training epochs and batches (use '-b' and '-e').
* add '--noval' to tell the program not use validation set during training.
* use '--custom_val_cases XXX YYY ...' and set fold to 'all' to manually assign validation set cases.
* use '--save_every_epoch' to save models from all epochs.
* add '--softmax' to save softmax values of validation set samples.
===============
== INFERENCE ==
===============
* add '--selected_cases XXX YYY ...' when inference will only predict the selected test subjects (XXX YYY ...) .
* add '--softmax' to save softmax values of test set samples.
============
== OTHERS ==
============
* removed unused codes.
* minor bug fixes...

using model stored in  /Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['0']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
selected cases to predict: ['0']
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, ['all']
set max_num_epochs=300
set num_batches_per_epoch=250
no validation set? False
using the following model files:  ['/Users/theodoretranos/Desktop/DeepWMH/models/nnUNet/3d_fullres/Task002_FinalModel/nnUNetTrainerV2__nnUNetPlansv2.1/all/model_best.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "/Users/theodoretranos/anaconda3/envs/brain2/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict_simple.py", line 214, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 412, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 211, in predict_cases
    for preprocessed in preprocessing:
  File "/Users/theodoretranos/Desktop/DeepWMH/nnUNet_for_DeepWMH-develop/nnunet/inference/predict.py", line 112, in preprocess_multithreaded
    pr.start()
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/theodoretranos/anaconda3/envs/brain2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Generic_UNet.__init__.<locals>.<lambda>'

>>> ** Unexpected return value "1" from command:

>>> nnUNet_predict -i /Users/theodoretranos/Desktop/DeepWMH/output/001_Preprocessed_Images -o /Users/theodoretranos/Desktop/DeepWMH/output/002_Segmentations/001_raw -tr nnUNetTrainerV2 -m 3d_fullres -p nnUNetPlansv2.1 -t Task002_FinalModel -f all -chk model_best --disable_post_processing --selected_cases 0 

>>> ** Process will exit now.

Theodore Tranos

**Comment by thtranos** [comment] 2024-01-24 09:09
Could it be that i'm passing file.nii instead of file.nii.gz at input?

**Comment by lchdl** [comment] 2024-01-24 11:40
Hi Theodore Tranos @thtranos, 

The problem is very similar to this issue posted under the nnU-Net repository: https://github.com/MIC-DKFZ/nnUNet/issues/589. Have a look if you're interested. It's related to running nnU-Net on Windows, but I think it's the same on Mac too, since it also reported the same error message, which is caused by **Python multiprocessing**.

So the final solution might involve **replacing multiprocessing in the nnU-Net** inference stage **to a single thread implementation**. It might slow down the inference speed, but I think it's worth it. But since I don't have a Mac environment and I currently don't have enough spare time to work on this, reproducing your problem on my side might be a little difficult. Maybe in the near future, I will create a new branch for https://github.com/lchdl/nnUNet_for_DeepWMH so that Mac users can run DeepWMH smoothly. Sorry for that :(.

At present, the fastest and easiest way to run DeepWMH for you is to use a typical Linux-based system (such as Ubuntu).

**Comment by thtranos** [comment] 2024-01-25 09:21
@lchdl Don't worry! You already did wonders helping me out!

Closely I'll have a Ubuntu distribution available with the desired GPU so hopefully i'll have no problems replicating the inference!

Whatsoever, I think that I'm close running it on MAC too, I'll check out the issue you referenced.

If I'm to make it successfuly run on MAC, I'll notify you so you can help future people who may want to run it to MAC!

Thanks for your dedication and your time,

Theodore Tranos

**Comment by thtranos** [comment] 2024-01-25 14:34
Also if available and possible, could you provide me with the RAM specs you used when you made these experiments? Seems like it needs alot of memory!

**Comment by thtranos** [comment] 2024-01-25 14:41
Also, I resolved the problem that I had with nnUnet.

I needed to change the lambda function in an entity called Generic_UNet inside the generic_UNet.py

I just needed to replace the lambda function existed inside the class.

Replaced:

`self.upscale_logits_ops.append(lambda x: x)`

to

`self.upscale_logits_ops.append(torch.nn.Identity())`

I hope this potentially helps someone who may encounter the same problem.
Link of the respectful issue thread: https://github.com/MIC-DKFZ/nnUNet/issues/589

Theodore Tranos

**Comment by lchdl** [comment] 2024-01-25 15:03
Hi thtranos,

Training a network from scratch needs a lot of memory, since the pipeline needs to load many NIFTI files into memory for the NLL anomaly score computation. I ran these experiments on a server with **256G** RAM and 56 CPU cores. If you want to lower the RAM usage, consider lowering the **num_workers** (number of parallel jobs) defined in **lesion_analysis.py, line 366**. The default value was set to 8 for speeding up the NLL calculation process, maybe it was set too high. 

Another thing worth noting is that if you want to train a network from scratch, the image registration step can be very time-consuming. Therefore, it is recommended that you run the experiment on a **CPU cluster** with at least one CUDA GPU available.

Finally, excellent job on resolving the issue related to nnU-Net! Could you please create a pull request on https://github.com/lchdl/nnUNet_for_DeepWMH so that I can update the code? I will leave this issue open in case others find it useful.

**Comment by thtranos** [comment] 2024-01-25 16:50
i'm not very familiar with github and I'm afraid of not doing something that will affect the files here. You can easily incorporate my change (it's just this line change on nnUNet_for_DeepWMH-develop > nnunet > network_architecture > generic_UNet.py at line 368 as mentioned earlier)

Previously I was talking about inference/evaluation and not training. Right now I was running it about an hour on my pc for a single patient and it used 16-25 GB of RAM which is enormous and eventually killed the process.

I'm glad that my association may potentially help any future individual with the same issue!

**Comment by lchdl** [comment] 2024-01-26 04:59
Hi thtranos,

Are you performing inference on a Mac? Typically, the inference shouldn't take too long only for a single patient. Have you been able to successfully execute the entire inference stage?

**Comment by lchdl** [comment] 2024-01-26 05:20
@thtranos 

[**nnUNet_for_DeepWMH** ](https://github.com/lchdl/nnUNet_for_DeepWMH) is now fixed. 

See:
https://github.com/lchdl/nnUNet_for_DeepWMH/commit/3509d4e02f68919925a5403f5586fcf6e6a19ea5
for more details.

This will enable **Mac** users to run DeepWMH smoothly. Please let me know if you encounter any other problems.

**Comment by thtranos** [comment] 2024-02-19 13:57
Greetings to everyone, I would like to apologize for the late response.

My new distribution of Ubuntu Unity + TitanX is ready, I installed everything as readme says and I pass the tests.

I am trying to run inference now and I am waiting for the preprocessing.

This is what I'm seeing on terminal

```
[*] Checking system integrity, please wait...
[*] ANTs version: "ANTs Version: 2.5.1-gb909304 Compiled: Jan 24 2024 20:11:58  ".
[*] OK.
model file is valid.

Pre-processing test images for prediction.
preprocessing : |                  | 0% << 10m32s
```

On the prompt, there's an argument that specifies gpu_id, i left that without an input (as I don't really know what to give), could it be this that it takes so much time or is it expected to last that long?

If I have any progression I will let you know!

Theodore Tranos

**Comment by lchdl** [comment] 2024-02-20 04:48
@thtranos, `gpu_id` is used for servers with multiple GPUs installed in the same machine. For example, if you have 4 GPUs installed in the machine and only want to use the 3rd one for running the inference, set `gpu_id=2`. For desktop users, typically with one GPU, just set it to `gpu_id=0` or leave it at the default setting.

**Comment by thtranos** [comment] 2024-02-20 14:53
I have good news! I made it work afterall!

It took about 13minutes for 1 patient. (my pc crashed 2-3 times for some reason and I had to rerun it, either because or RAM or GPU but I am not entirely sure!)

One last thing that I would like to kindly ask is, out of all the content that is outputed, which one should I consider to get the segmentation mask of the lesions for the z axis? My guess is that I have to manipulate the .nii file and extract the data I need out of the 3 dimensions.

Theodore Tranos

**Comment by lchdl** [comment] 2024-02-20 15:14
Usually, you will need software to view NIFTI (*.nii or *.nii.gz) files, such as MIPAV (https://mipav.cit.nih.gov/), which will visualize the volume for you.

**Comment by thtranos** [comment] 2024-02-20 15:24
I'll probably handle it using Python, but out of all the folders that are generated, which .nii should I use as the final output data? There are 3 folders:

1. _raw
2. _postproc_3mm
3. postproc_fov

Theodore Tranos

**Comment by lchdl** [comment] 2024-02-20 15:31
@thtranos, look at the last several lines of output from the console; they will show you where the images and segmentations are stored. Usually it will be "003_postproc_fov".

**Closed as completed** 2024-03-30 17:08 UTC
Labels: bug
